[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "_site"

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "staging" }
